# Generated by Django 5.2 on 2025-04-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_genre',
        ),
    ]
